"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TonConnectUIProvider } from '@tonconnect/ui-react';
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TonConnectUIProvider manifestUrl="http://localhost:3000/tonconnect-manifest.json">
        {children}
        </TonConnectUIProvider>
        </body>
    </html>
  );
}
